// automatically generated by the FlatBuffers compiler, do not modify

package org.knime.flatbuffers.flatc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class IntColumn extends Table {
  public static IntColumn getRootAsIntColumn(ByteBuffer _bb) { return getRootAsIntColumn(_bb, new IntColumn()); }
  public static IntColumn getRootAsIntColumn(ByteBuffer _bb, IntColumn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public IntColumn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int values(int j) { int o = __offset(4); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int valuesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer valuesAsByteBuffer() { return __vector_as_bytebuffer(4, 4); }

  public static int createIntColumn(FlatBufferBuilder builder,
      int valuesOffset) {
    builder.startObject(1);
    IntColumn.addValues(builder, valuesOffset);
    return IntColumn.endIntColumn(builder);
  }

  public static void startIntColumn(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValues(FlatBufferBuilder builder, int valuesOffset) { builder.addOffset(0, valuesOffset, 0); }
  public static int createValuesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endIntColumn(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

