// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autocompletesuggestions.proto

package org.knime.python.kernel.proto;

public final class ProtobufAutocompleteSuggestions {
  private ProtobufAutocompleteSuggestions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AutocompleteSuggestionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;
    /**
     * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
     */
    java.util.List<org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion> 
        getAutocompleteSuggestionList();
    /**
     * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
     */
    org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion getAutocompleteSuggestion(int index);
    /**
     * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
     */
    int getAutocompleteSuggestionCount();
    /**
     * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
     */
    java.util.List<? extends org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestionOrBuilder> 
        getAutocompleteSuggestionOrBuilderList();
    /**
     * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
     */
    org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestionOrBuilder getAutocompleteSuggestionOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code knime.AutocompleteSuggestions}
   */
  public static final class AutocompleteSuggestions extends
      com.google.protobuf.GeneratedMessage
      implements AutocompleteSuggestionsOrBuilder {
    // Use AutocompleteSuggestions.newBuilder() to construct.
    private AutocompleteSuggestions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AutocompleteSuggestions(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AutocompleteSuggestions defaultInstance;
    public static AutocompleteSuggestions getDefaultInstance() {
      return defaultInstance;
    }

    public AutocompleteSuggestions getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AutocompleteSuggestions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                autocompleteSuggestion_ = new java.util.ArrayList<org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion>();
                mutable_bitField0_ |= 0x00000001;
              }
              autocompleteSuggestion_.add(input.readMessage(org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          autocompleteSuggestion_ = java.util.Collections.unmodifiableList(autocompleteSuggestion_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.internal_static_knime_AutocompleteSuggestions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.internal_static_knime_AutocompleteSuggestions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.class, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.Builder.class);
    }

    public static com.google.protobuf.Parser<AutocompleteSuggestions> PARSER =
        new com.google.protobuf.AbstractParser<AutocompleteSuggestions>() {
      public AutocompleteSuggestions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AutocompleteSuggestions(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AutocompleteSuggestions> getParserForType() {
      return PARSER;
    }

    public interface AutocompleteSuggestionOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // required string type = 2;
      /**
       * <code>required string type = 2;</code>
       */
      boolean hasType();
      /**
       * <code>required string type = 2;</code>
       */
      java.lang.String getType();
      /**
       * <code>required string type = 2;</code>
       */
      com.google.protobuf.ByteString
          getTypeBytes();

      // required string doc = 3;
      /**
       * <code>required string doc = 3;</code>
       */
      boolean hasDoc();
      /**
       * <code>required string doc = 3;</code>
       */
      java.lang.String getDoc();
      /**
       * <code>required string doc = 3;</code>
       */
      com.google.protobuf.ByteString
          getDocBytes();
    }
    /**
     * Protobuf type {@code knime.AutocompleteSuggestions.AutocompleteSuggestion}
     */
    public static final class AutocompleteSuggestion extends
        com.google.protobuf.GeneratedMessage
        implements AutocompleteSuggestionOrBuilder {
      // Use AutocompleteSuggestion.newBuilder() to construct.
      private AutocompleteSuggestion(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private AutocompleteSuggestion(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final AutocompleteSuggestion defaultInstance;
      public static AutocompleteSuggestion getDefaultInstance() {
        return defaultInstance;
      }

      public AutocompleteSuggestion getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private AutocompleteSuggestion(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                type_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                doc_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.internal_static_knime_AutocompleteSuggestions_AutocompleteSuggestion_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.internal_static_knime_AutocompleteSuggestions_AutocompleteSuggestion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.class, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder.class);
      }

      public static com.google.protobuf.Parser<AutocompleteSuggestion> PARSER =
          new com.google.protobuf.AbstractParser<AutocompleteSuggestion>() {
        public AutocompleteSuggestion parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new AutocompleteSuggestion(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<AutocompleteSuggestion> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string type = 2;
      public static final int TYPE_FIELD_NUMBER = 2;
      private java.lang.Object type_;
      /**
       * <code>required string type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string doc = 3;
      public static final int DOC_FIELD_NUMBER = 3;
      private java.lang.Object doc_;
      /**
       * <code>required string doc = 3;</code>
       */
      public boolean hasDoc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string doc = 3;</code>
       */
      public java.lang.String getDoc() {
        java.lang.Object ref = doc_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            doc_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string doc = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDocBytes() {
        java.lang.Object ref = doc_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          doc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        name_ = "";
        type_ = "";
        doc_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDoc()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTypeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getDocBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTypeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getDocBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code knime.AutocompleteSuggestions.AutocompleteSuggestion}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.internal_static_knime_AutocompleteSuggestions_AutocompleteSuggestion_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.internal_static_knime_AutocompleteSuggestions_AutocompleteSuggestion_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.class, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder.class);
        }

        // Construct using org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          doc_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.internal_static_knime_AutocompleteSuggestions_AutocompleteSuggestion_descriptor;
        }

        public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion getDefaultInstanceForType() {
          return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.getDefaultInstance();
        }

        public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion build() {
          org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion buildPartial() {
          org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion result = new org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.doc_ = doc_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion) {
            return mergeFrom((org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion other) {
          if (other == org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasType()) {
            bitField0_ |= 0x00000002;
            type_ = other.type_;
            onChanged();
          }
          if (other.hasDoc()) {
            bitField0_ |= 0x00000004;
            doc_ = other.doc_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasType()) {
            
            return false;
          }
          if (!hasDoc()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // required string type = 2;
        private java.lang.Object type_ = "";
        /**
         * <code>required string type = 2;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string type = 2;</code>
         */
        public java.lang.String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            type_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string type = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTypeBytes() {
          java.lang.Object ref = type_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            type_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string type = 2;</code>
         */
        public Builder setType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 2;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 2;</code>
         */
        public Builder setTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }

        // required string doc = 3;
        private java.lang.Object doc_ = "";
        /**
         * <code>required string doc = 3;</code>
         */
        public boolean hasDoc() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string doc = 3;</code>
         */
        public java.lang.String getDoc() {
          java.lang.Object ref = doc_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            doc_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string doc = 3;</code>
         */
        public com.google.protobuf.ByteString
            getDocBytes() {
          java.lang.Object ref = doc_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            doc_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string doc = 3;</code>
         */
        public Builder setDoc(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          doc_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string doc = 3;</code>
         */
        public Builder clearDoc() {
          bitField0_ = (bitField0_ & ~0x00000004);
          doc_ = getDefaultInstance().getDoc();
          onChanged();
          return this;
        }
        /**
         * <code>required string doc = 3;</code>
         */
        public Builder setDocBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          doc_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:knime.AutocompleteSuggestions.AutocompleteSuggestion)
      }

      static {
        defaultInstance = new AutocompleteSuggestion(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:knime.AutocompleteSuggestions.AutocompleteSuggestion)
    }

    // repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;
    public static final int AUTOCOMPLETESUGGESTION_FIELD_NUMBER = 1;
    private java.util.List<org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion> autocompleteSuggestion_;
    /**
     * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
     */
    public java.util.List<org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion> getAutocompleteSuggestionList() {
      return autocompleteSuggestion_;
    }
    /**
     * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
     */
    public java.util.List<? extends org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestionOrBuilder> 
        getAutocompleteSuggestionOrBuilderList() {
      return autocompleteSuggestion_;
    }
    /**
     * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
     */
    public int getAutocompleteSuggestionCount() {
      return autocompleteSuggestion_.size();
    }
    /**
     * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
     */
    public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion getAutocompleteSuggestion(int index) {
      return autocompleteSuggestion_.get(index);
    }
    /**
     * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
     */
    public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestionOrBuilder getAutocompleteSuggestionOrBuilder(
        int index) {
      return autocompleteSuggestion_.get(index);
    }

    private void initFields() {
      autocompleteSuggestion_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getAutocompleteSuggestionCount(); i++) {
        if (!getAutocompleteSuggestion(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < autocompleteSuggestion_.size(); i++) {
        output.writeMessage(1, autocompleteSuggestion_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < autocompleteSuggestion_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, autocompleteSuggestion_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code knime.AutocompleteSuggestions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.internal_static_knime_AutocompleteSuggestions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.internal_static_knime_AutocompleteSuggestions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.class, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.Builder.class);
      }

      // Construct using org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAutocompleteSuggestionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (autocompleteSuggestionBuilder_ == null) {
          autocompleteSuggestion_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          autocompleteSuggestionBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.internal_static_knime_AutocompleteSuggestions_descriptor;
      }

      public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions getDefaultInstanceForType() {
        return org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.getDefaultInstance();
      }

      public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions build() {
        org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions buildPartial() {
        org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions result = new org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions(this);
        int from_bitField0_ = bitField0_;
        if (autocompleteSuggestionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            autocompleteSuggestion_ = java.util.Collections.unmodifiableList(autocompleteSuggestion_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.autocompleteSuggestion_ = autocompleteSuggestion_;
        } else {
          result.autocompleteSuggestion_ = autocompleteSuggestionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions) {
          return mergeFrom((org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions other) {
        if (other == org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.getDefaultInstance()) return this;
        if (autocompleteSuggestionBuilder_ == null) {
          if (!other.autocompleteSuggestion_.isEmpty()) {
            if (autocompleteSuggestion_.isEmpty()) {
              autocompleteSuggestion_ = other.autocompleteSuggestion_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAutocompleteSuggestionIsMutable();
              autocompleteSuggestion_.addAll(other.autocompleteSuggestion_);
            }
            onChanged();
          }
        } else {
          if (!other.autocompleteSuggestion_.isEmpty()) {
            if (autocompleteSuggestionBuilder_.isEmpty()) {
              autocompleteSuggestionBuilder_.dispose();
              autocompleteSuggestionBuilder_ = null;
              autocompleteSuggestion_ = other.autocompleteSuggestion_;
              bitField0_ = (bitField0_ & ~0x00000001);
              autocompleteSuggestionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAutocompleteSuggestionFieldBuilder() : null;
            } else {
              autocompleteSuggestionBuilder_.addAllMessages(other.autocompleteSuggestion_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAutocompleteSuggestionCount(); i++) {
          if (!getAutocompleteSuggestion(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;
      private java.util.List<org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion> autocompleteSuggestion_ =
        java.util.Collections.emptyList();
      private void ensureAutocompleteSuggestionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          autocompleteSuggestion_ = new java.util.ArrayList<org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion>(autocompleteSuggestion_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestionOrBuilder> autocompleteSuggestionBuilder_;

      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public java.util.List<org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion> getAutocompleteSuggestionList() {
        if (autocompleteSuggestionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(autocompleteSuggestion_);
        } else {
          return autocompleteSuggestionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public int getAutocompleteSuggestionCount() {
        if (autocompleteSuggestionBuilder_ == null) {
          return autocompleteSuggestion_.size();
        } else {
          return autocompleteSuggestionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion getAutocompleteSuggestion(int index) {
        if (autocompleteSuggestionBuilder_ == null) {
          return autocompleteSuggestion_.get(index);
        } else {
          return autocompleteSuggestionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public Builder setAutocompleteSuggestion(
          int index, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion value) {
        if (autocompleteSuggestionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAutocompleteSuggestionIsMutable();
          autocompleteSuggestion_.set(index, value);
          onChanged();
        } else {
          autocompleteSuggestionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public Builder setAutocompleteSuggestion(
          int index, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder builderForValue) {
        if (autocompleteSuggestionBuilder_ == null) {
          ensureAutocompleteSuggestionIsMutable();
          autocompleteSuggestion_.set(index, builderForValue.build());
          onChanged();
        } else {
          autocompleteSuggestionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public Builder addAutocompleteSuggestion(org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion value) {
        if (autocompleteSuggestionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAutocompleteSuggestionIsMutable();
          autocompleteSuggestion_.add(value);
          onChanged();
        } else {
          autocompleteSuggestionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public Builder addAutocompleteSuggestion(
          int index, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion value) {
        if (autocompleteSuggestionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAutocompleteSuggestionIsMutable();
          autocompleteSuggestion_.add(index, value);
          onChanged();
        } else {
          autocompleteSuggestionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public Builder addAutocompleteSuggestion(
          org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder builderForValue) {
        if (autocompleteSuggestionBuilder_ == null) {
          ensureAutocompleteSuggestionIsMutable();
          autocompleteSuggestion_.add(builderForValue.build());
          onChanged();
        } else {
          autocompleteSuggestionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public Builder addAutocompleteSuggestion(
          int index, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder builderForValue) {
        if (autocompleteSuggestionBuilder_ == null) {
          ensureAutocompleteSuggestionIsMutable();
          autocompleteSuggestion_.add(index, builderForValue.build());
          onChanged();
        } else {
          autocompleteSuggestionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public Builder addAllAutocompleteSuggestion(
          java.lang.Iterable<? extends org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion> values) {
        if (autocompleteSuggestionBuilder_ == null) {
          ensureAutocompleteSuggestionIsMutable();
          super.addAll(values, autocompleteSuggestion_);
          onChanged();
        } else {
          autocompleteSuggestionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public Builder clearAutocompleteSuggestion() {
        if (autocompleteSuggestionBuilder_ == null) {
          autocompleteSuggestion_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          autocompleteSuggestionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public Builder removeAutocompleteSuggestion(int index) {
        if (autocompleteSuggestionBuilder_ == null) {
          ensureAutocompleteSuggestionIsMutable();
          autocompleteSuggestion_.remove(index);
          onChanged();
        } else {
          autocompleteSuggestionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder getAutocompleteSuggestionBuilder(
          int index) {
        return getAutocompleteSuggestionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestionOrBuilder getAutocompleteSuggestionOrBuilder(
          int index) {
        if (autocompleteSuggestionBuilder_ == null) {
          return autocompleteSuggestion_.get(index);  } else {
          return autocompleteSuggestionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public java.util.List<? extends org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestionOrBuilder> 
           getAutocompleteSuggestionOrBuilderList() {
        if (autocompleteSuggestionBuilder_ != null) {
          return autocompleteSuggestionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(autocompleteSuggestion_);
        }
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder addAutocompleteSuggestionBuilder() {
        return getAutocompleteSuggestionFieldBuilder().addBuilder(
            org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.getDefaultInstance());
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder addAutocompleteSuggestionBuilder(
          int index) {
        return getAutocompleteSuggestionFieldBuilder().addBuilder(
            index, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.getDefaultInstance());
      }
      /**
       * <code>repeated .knime.AutocompleteSuggestions.AutocompleteSuggestion autocompleteSuggestion = 1;</code>
       */
      public java.util.List<org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder> 
           getAutocompleteSuggestionBuilderList() {
        return getAutocompleteSuggestionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestionOrBuilder> 
          getAutocompleteSuggestionFieldBuilder() {
        if (autocompleteSuggestionBuilder_ == null) {
          autocompleteSuggestionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestion.Builder, org.knime.python.kernel.proto.ProtobufAutocompleteSuggestions.AutocompleteSuggestions.AutocompleteSuggestionOrBuilder>(
                  autocompleteSuggestion_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          autocompleteSuggestion_ = null;
        }
        return autocompleteSuggestionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:knime.AutocompleteSuggestions)
    }

    static {
      defaultInstance = new AutocompleteSuggestions(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:knime.AutocompleteSuggestions)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_knime_AutocompleteSuggestions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_knime_AutocompleteSuggestions_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_knime_AutocompleteSuggestions_AutocompleteSuggestion_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_knime_AutocompleteSuggestions_AutocompleteSuggestion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035autocompletesuggestions.proto\022\005knime\"\263" +
      "\001\n\027AutocompleteSuggestions\022U\n\026autocomple" +
      "teSuggestion\030\001 \003(\01325.knime.AutocompleteS" +
      "uggestions.AutocompleteSuggestion\032A\n\026Aut" +
      "ocompleteSuggestion\022\014\n\004name\030\001 \002(\t\022\014\n\004typ" +
      "e\030\002 \002(\t\022\013\n\003doc\030\003 \002(\tB@\n\035org.knime.python" +
      ".kernel.protoB\037ProtobufAutocompleteSugge" +
      "stions"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_knime_AutocompleteSuggestions_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_knime_AutocompleteSuggestions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_knime_AutocompleteSuggestions_descriptor,
              new java.lang.String[] { "AutocompleteSuggestion", });
          internal_static_knime_AutocompleteSuggestions_AutocompleteSuggestion_descriptor =
            internal_static_knime_AutocompleteSuggestions_descriptor.getNestedTypes().get(0);
          internal_static_knime_AutocompleteSuggestions_AutocompleteSuggestion_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_knime_AutocompleteSuggestions_AutocompleteSuggestion_descriptor,
              new java.lang.String[] { "Name", "Type", "Doc", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
