// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sqlOutput.proto

package org.knime.python.kernel.proto;

public final class ProtobufKnimeSQLOutput {
  private ProtobufKnimeSQLOutput() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SQLOutputOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string query = 1;
    /**
     * <code>required string query = 1;</code>
     */
    boolean hasQuery();
    /**
     * <code>required string query = 1;</code>
     */
    java.lang.String getQuery();
    /**
     * <code>required string query = 1;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    // optional .knime.HiveOutput hive = 2;
    /**
     * <code>optional .knime.HiveOutput hive = 2;</code>
     */
    boolean hasHive();
    /**
     * <code>optional .knime.HiveOutput hive = 2;</code>
     */
    org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput getHive();
    /**
     * <code>optional .knime.HiveOutput hive = 2;</code>
     */
    org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutputOrBuilder getHiveOrBuilder();
  }
  /**
   * Protobuf type {@code knime.SQLOutput}
   */
  public static final class SQLOutput extends
      com.google.protobuf.GeneratedMessage
      implements SQLOutputOrBuilder {
    // Use SQLOutput.newBuilder() to construct.
    private SQLOutput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SQLOutput(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SQLOutput defaultInstance;
    public static SQLOutput getDefaultInstance() {
      return defaultInstance;
    }

    public SQLOutput getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SQLOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              query_ = input.readBytes();
              break;
            }
            case 18: {
              org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = hive_.toBuilder();
              }
              hive_ = input.readMessage(org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hive_);
                hive_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.internal_static_knime_SQLOutput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.internal_static_knime_SQLOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput.class, org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput.Builder.class);
    }

    public static com.google.protobuf.Parser<SQLOutput> PARSER =
        new com.google.protobuf.AbstractParser<SQLOutput>() {
      public SQLOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SQLOutput(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SQLOutput> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string query = 1;
    public static final int QUERY_FIELD_NUMBER = 1;
    private java.lang.Object query_;
    /**
     * <code>required string query = 1;</code>
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string query = 1;</code>
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          query_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string query = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .knime.HiveOutput hive = 2;
    public static final int HIVE_FIELD_NUMBER = 2;
    private org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput hive_;
    /**
     * <code>optional .knime.HiveOutput hive = 2;</code>
     */
    public boolean hasHive() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .knime.HiveOutput hive = 2;</code>
     */
    public org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput getHive() {
      return hive_;
    }
    /**
     * <code>optional .knime.HiveOutput hive = 2;</code>
     */
    public org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutputOrBuilder getHiveOrBuilder() {
      return hive_;
    }

    private void initFields() {
      query_ = "";
      hive_ = org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasQuery()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasHive()) {
        if (!getHive().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getQueryBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, hive_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getQueryBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, hive_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code knime.SQLOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.internal_static_knime_SQLOutput_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.internal_static_knime_SQLOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput.class, org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput.Builder.class);
      }

      // Construct using org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHiveFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        query_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (hiveBuilder_ == null) {
          hive_ = org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.getDefaultInstance();
        } else {
          hiveBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.internal_static_knime_SQLOutput_descriptor;
      }

      public org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput getDefaultInstanceForType() {
        return org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput.getDefaultInstance();
      }

      public org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput build() {
        org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput buildPartial() {
        org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput result = new org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.query_ = query_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (hiveBuilder_ == null) {
          result.hive_ = hive_;
        } else {
          result.hive_ = hiveBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput) {
          return mergeFrom((org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput other) {
        if (other == org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput.getDefaultInstance()) return this;
        if (other.hasQuery()) {
          bitField0_ |= 0x00000001;
          query_ = other.query_;
          onChanged();
        }
        if (other.hasHive()) {
          mergeHive(other.getHive());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasQuery()) {
          
          return false;
        }
        if (hasHive()) {
          if (!getHive().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.knime.python.kernel.proto.ProtobufKnimeSQLOutput.SQLOutput) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string query = 1;
      private java.lang.Object query_ = "";
      /**
       * <code>required string query = 1;</code>
       */
      public boolean hasQuery() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string query = 1;</code>
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string query = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string query = 1;</code>
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string query = 1;</code>
       */
      public Builder clearQuery() {
        bitField0_ = (bitField0_ & ~0x00000001);
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>required string query = 1;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }

      // optional .knime.HiveOutput hive = 2;
      private org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput hive_ = org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput, org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.Builder, org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutputOrBuilder> hiveBuilder_;
      /**
       * <code>optional .knime.HiveOutput hive = 2;</code>
       */
      public boolean hasHive() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .knime.HiveOutput hive = 2;</code>
       */
      public org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput getHive() {
        if (hiveBuilder_ == null) {
          return hive_;
        } else {
          return hiveBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .knime.HiveOutput hive = 2;</code>
       */
      public Builder setHive(org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput value) {
        if (hiveBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hive_ = value;
          onChanged();
        } else {
          hiveBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .knime.HiveOutput hive = 2;</code>
       */
      public Builder setHive(
          org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.Builder builderForValue) {
        if (hiveBuilder_ == null) {
          hive_ = builderForValue.build();
          onChanged();
        } else {
          hiveBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .knime.HiveOutput hive = 2;</code>
       */
      public Builder mergeHive(org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput value) {
        if (hiveBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              hive_ != org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.getDefaultInstance()) {
            hive_ =
              org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.newBuilder(hive_).mergeFrom(value).buildPartial();
          } else {
            hive_ = value;
          }
          onChanged();
        } else {
          hiveBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .knime.HiveOutput hive = 2;</code>
       */
      public Builder clearHive() {
        if (hiveBuilder_ == null) {
          hive_ = org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.getDefaultInstance();
          onChanged();
        } else {
          hiveBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .knime.HiveOutput hive = 2;</code>
       */
      public org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.Builder getHiveBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHiveFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .knime.HiveOutput hive = 2;</code>
       */
      public org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutputOrBuilder getHiveOrBuilder() {
        if (hiveBuilder_ != null) {
          return hiveBuilder_.getMessageOrBuilder();
        } else {
          return hive_;
        }
      }
      /**
       * <code>optional .knime.HiveOutput hive = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput, org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.Builder, org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutputOrBuilder> 
          getHiveFieldBuilder() {
        if (hiveBuilder_ == null) {
          hiveBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput, org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.Builder, org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutputOrBuilder>(
                  hive_,
                  getParentForChildren(),
                  isClean());
          hive_ = null;
        }
        return hiveBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:knime.SQLOutput)
    }

    static {
      defaultInstance = new SQLOutput(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:knime.SQLOutput)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_knime_SQLOutput_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_knime_SQLOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017sqlOutput.proto\022\005knime\032\020hiveOutput.pro" +
      "to\";\n\tSQLOutput\022\r\n\005query\030\001 \002(\t\022\037\n\004hive\030\002" +
      " \001(\0132\021.knime.HiveOutputB7\n\035org.knime.pyt" +
      "hon.kernel.protoB\026ProtobufKnimeSQLOutput"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_knime_SQLOutput_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_knime_SQLOutput_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_knime_SQLOutput_descriptor,
              new java.lang.String[] { "Query", "Hive", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
