// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hiveOutput.proto

package org.knime.python.kernel.proto;

public final class ProtobufKnimeHiveOutput {
  private ProtobufKnimeHiveOutput() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HiveOutputOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string tableName = 1;
    /**
     * <code>required string tableName = 1;</code>
     */
    boolean hasTableName();
    /**
     * <code>required string tableName = 1;</code>
     */
    java.lang.String getTableName();
    /**
     * <code>required string tableName = 1;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    // repeated string columnNames = 2;
    /**
     * <code>repeated string columnNames = 2;</code>
     */
    java.util.List<java.lang.String>
    getColumnNamesList();
    /**
     * <code>repeated string columnNames = 2;</code>
     */
    int getColumnNamesCount();
    /**
     * <code>repeated string columnNames = 2;</code>
     */
    java.lang.String getColumnNames(int index);
    /**
     * <code>repeated string columnNames = 2;</code>
     */
    com.google.protobuf.ByteString
        getColumnNamesBytes(int index);

    // repeated string columnType = 3;
    /**
     * <code>repeated string columnType = 3;</code>
     */
    java.util.List<java.lang.String>
    getColumnTypeList();
    /**
     * <code>repeated string columnType = 3;</code>
     */
    int getColumnTypeCount();
    /**
     * <code>repeated string columnType = 3;</code>
     */
    java.lang.String getColumnType(int index);
    /**
     * <code>repeated string columnType = 3;</code>
     */
    com.google.protobuf.ByteString
        getColumnTypeBytes(int index);

    // repeated string partitionColumnNames = 4;
    /**
     * <code>repeated string partitionColumnNames = 4;</code>
     */
    java.util.List<java.lang.String>
    getPartitionColumnNamesList();
    /**
     * <code>repeated string partitionColumnNames = 4;</code>
     */
    int getPartitionColumnNamesCount();
    /**
     * <code>repeated string partitionColumnNames = 4;</code>
     */
    java.lang.String getPartitionColumnNames(int index);
    /**
     * <code>repeated string partitionColumnNames = 4;</code>
     */
    com.google.protobuf.ByteString
        getPartitionColumnNamesBytes(int index);

    // required string fileName = 5;
    /**
     * <code>required string fileName = 5;</code>
     */
    boolean hasFileName();
    /**
     * <code>required string fileName = 5;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>required string fileName = 5;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    // required bool tableExist = 6;
    /**
     * <code>required bool tableExist = 6;</code>
     */
    boolean hasTableExist();
    /**
     * <code>required bool tableExist = 6;</code>
     */
    boolean getTableExist();

    // required bool dropTable = 7;
    /**
     * <code>required bool dropTable = 7;</code>
     */
    boolean hasDropTable();
    /**
     * <code>required bool dropTable = 7;</code>
     */
    boolean getDropTable();

    // required string delimiter = 8;
    /**
     * <code>required string delimiter = 8;</code>
     */
    boolean hasDelimiter();
    /**
     * <code>required string delimiter = 8;</code>
     */
    java.lang.String getDelimiter();
    /**
     * <code>required string delimiter = 8;</code>
     */
    com.google.protobuf.ByteString
        getDelimiterBytes();
  }
  /**
   * Protobuf type {@code knime.HiveOutput}
   */
  public static final class HiveOutput extends
      com.google.protobuf.GeneratedMessage
      implements HiveOutputOrBuilder {
    // Use HiveOutput.newBuilder() to construct.
    private HiveOutput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HiveOutput(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HiveOutput defaultInstance;
    public static HiveOutput getDefaultInstance() {
      return defaultInstance;
    }

    public HiveOutput getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HiveOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              tableName_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                columnNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              columnNames_.add(input.readBytes());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                columnType_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              columnType_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                partitionColumnNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              partitionColumnNames_.add(input.readBytes());
              break;
            }
            case 42: {
              bitField0_ |= 0x00000002;
              fileName_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000004;
              tableExist_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000008;
              dropTable_ = input.readBool();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000010;
              delimiter_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          columnNames_ = new com.google.protobuf.UnmodifiableLazyStringList(columnNames_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          columnType_ = new com.google.protobuf.UnmodifiableLazyStringList(columnType_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          partitionColumnNames_ = new com.google.protobuf.UnmodifiableLazyStringList(partitionColumnNames_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.internal_static_knime_HiveOutput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.internal_static_knime_HiveOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.class, org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.Builder.class);
    }

    public static com.google.protobuf.Parser<HiveOutput> PARSER =
        new com.google.protobuf.AbstractParser<HiveOutput>() {
      public HiveOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HiveOutput(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HiveOutput> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string tableName = 1;
    public static final int TABLENAME_FIELD_NUMBER = 1;
    private java.lang.Object tableName_;
    /**
     * <code>required string tableName = 1;</code>
     */
    public boolean hasTableName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string tableName = 1;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tableName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tableName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string columnNames = 2;
    public static final int COLUMNNAMES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList columnNames_;
    /**
     * <code>repeated string columnNames = 2;</code>
     */
    public java.util.List<java.lang.String>
        getColumnNamesList() {
      return columnNames_;
    }
    /**
     * <code>repeated string columnNames = 2;</code>
     */
    public int getColumnNamesCount() {
      return columnNames_.size();
    }
    /**
     * <code>repeated string columnNames = 2;</code>
     */
    public java.lang.String getColumnNames(int index) {
      return columnNames_.get(index);
    }
    /**
     * <code>repeated string columnNames = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColumnNamesBytes(int index) {
      return columnNames_.getByteString(index);
    }

    // repeated string columnType = 3;
    public static final int COLUMNTYPE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList columnType_;
    /**
     * <code>repeated string columnType = 3;</code>
     */
    public java.util.List<java.lang.String>
        getColumnTypeList() {
      return columnType_;
    }
    /**
     * <code>repeated string columnType = 3;</code>
     */
    public int getColumnTypeCount() {
      return columnType_.size();
    }
    /**
     * <code>repeated string columnType = 3;</code>
     */
    public java.lang.String getColumnType(int index) {
      return columnType_.get(index);
    }
    /**
     * <code>repeated string columnType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getColumnTypeBytes(int index) {
      return columnType_.getByteString(index);
    }

    // repeated string partitionColumnNames = 4;
    public static final int PARTITIONCOLUMNNAMES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList partitionColumnNames_;
    /**
     * <code>repeated string partitionColumnNames = 4;</code>
     */
    public java.util.List<java.lang.String>
        getPartitionColumnNamesList() {
      return partitionColumnNames_;
    }
    /**
     * <code>repeated string partitionColumnNames = 4;</code>
     */
    public int getPartitionColumnNamesCount() {
      return partitionColumnNames_.size();
    }
    /**
     * <code>repeated string partitionColumnNames = 4;</code>
     */
    public java.lang.String getPartitionColumnNames(int index) {
      return partitionColumnNames_.get(index);
    }
    /**
     * <code>repeated string partitionColumnNames = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPartitionColumnNamesBytes(int index) {
      return partitionColumnNames_.getByteString(index);
    }

    // required string fileName = 5;
    public static final int FILENAME_FIELD_NUMBER = 5;
    private java.lang.Object fileName_;
    /**
     * <code>required string fileName = 5;</code>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string fileName = 5;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bool tableExist = 6;
    public static final int TABLEEXIST_FIELD_NUMBER = 6;
    private boolean tableExist_;
    /**
     * <code>required bool tableExist = 6;</code>
     */
    public boolean hasTableExist() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool tableExist = 6;</code>
     */
    public boolean getTableExist() {
      return tableExist_;
    }

    // required bool dropTable = 7;
    public static final int DROPTABLE_FIELD_NUMBER = 7;
    private boolean dropTable_;
    /**
     * <code>required bool dropTable = 7;</code>
     */
    public boolean hasDropTable() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool dropTable = 7;</code>
     */
    public boolean getDropTable() {
      return dropTable_;
    }

    // required string delimiter = 8;
    public static final int DELIMITER_FIELD_NUMBER = 8;
    private java.lang.Object delimiter_;
    /**
     * <code>required string delimiter = 8;</code>
     */
    public boolean hasDelimiter() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string delimiter = 8;</code>
     */
    public java.lang.String getDelimiter() {
      java.lang.Object ref = delimiter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          delimiter_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string delimiter = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDelimiterBytes() {
      java.lang.Object ref = delimiter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        delimiter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tableName_ = "";
      columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      columnType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      partitionColumnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      fileName_ = "";
      tableExist_ = false;
      dropTable_ = false;
      delimiter_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTableName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTableExist()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDropTable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDelimiter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTableNameBytes());
      }
      for (int i = 0; i < columnNames_.size(); i++) {
        output.writeBytes(2, columnNames_.getByteString(i));
      }
      for (int i = 0; i < columnType_.size(); i++) {
        output.writeBytes(3, columnType_.getByteString(i));
      }
      for (int i = 0; i < partitionColumnNames_.size(); i++) {
        output.writeBytes(4, partitionColumnNames_.getByteString(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(5, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(6, tableExist_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(7, dropTable_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(8, getDelimiterBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTableNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < columnNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(columnNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getColumnNamesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < columnType_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(columnType_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getColumnTypeList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < partitionColumnNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(partitionColumnNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPartitionColumnNamesList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, tableExist_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, dropTable_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getDelimiterBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code knime.HiveOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.internal_static_knime_HiveOutput_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.internal_static_knime_HiveOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.class, org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.Builder.class);
      }

      // Construct using org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tableName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        columnType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        partitionColumnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        tableExist_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        dropTable_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        delimiter_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.internal_static_knime_HiveOutput_descriptor;
      }

      public org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput getDefaultInstanceForType() {
        return org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.getDefaultInstance();
      }

      public org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput build() {
        org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput buildPartial() {
        org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput result = new org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tableName_ = tableName_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          columnNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              columnNames_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.columnNames_ = columnNames_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          columnType_ = new com.google.protobuf.UnmodifiableLazyStringList(
              columnType_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.columnType_ = columnType_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          partitionColumnNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              partitionColumnNames_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.partitionColumnNames_ = partitionColumnNames_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tableExist_ = tableExist_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dropTable_ = dropTable_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000010;
        }
        result.delimiter_ = delimiter_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput) {
          return mergeFrom((org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput other) {
        if (other == org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput.getDefaultInstance()) return this;
        if (other.hasTableName()) {
          bitField0_ |= 0x00000001;
          tableName_ = other.tableName_;
          onChanged();
        }
        if (!other.columnNames_.isEmpty()) {
          if (columnNames_.isEmpty()) {
            columnNames_ = other.columnNames_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureColumnNamesIsMutable();
            columnNames_.addAll(other.columnNames_);
          }
          onChanged();
        }
        if (!other.columnType_.isEmpty()) {
          if (columnType_.isEmpty()) {
            columnType_ = other.columnType_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureColumnTypeIsMutable();
            columnType_.addAll(other.columnType_);
          }
          onChanged();
        }
        if (!other.partitionColumnNames_.isEmpty()) {
          if (partitionColumnNames_.isEmpty()) {
            partitionColumnNames_ = other.partitionColumnNames_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePartitionColumnNamesIsMutable();
            partitionColumnNames_.addAll(other.partitionColumnNames_);
          }
          onChanged();
        }
        if (other.hasFileName()) {
          bitField0_ |= 0x00000010;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasTableExist()) {
          setTableExist(other.getTableExist());
        }
        if (other.hasDropTable()) {
          setDropTable(other.getDropTable());
        }
        if (other.hasDelimiter()) {
          bitField0_ |= 0x00000080;
          delimiter_ = other.delimiter_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTableName()) {
          
          return false;
        }
        if (!hasFileName()) {
          
          return false;
        }
        if (!hasTableExist()) {
          
          return false;
        }
        if (!hasDropTable()) {
          
          return false;
        }
        if (!hasDelimiter()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.knime.python.kernel.proto.ProtobufKnimeHiveOutput.HiveOutput) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string tableName = 1;
      private java.lang.Object tableName_ = "";
      /**
       * <code>required string tableName = 1;</code>
       */
      public boolean hasTableName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string tableName = 1;</code>
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tableName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tableName = 1;</code>
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tableName = 1;</code>
       */
      public Builder clearTableName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <code>required string tableName = 1;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tableName_ = value;
        onChanged();
        return this;
      }

      // repeated string columnNames = 2;
      private com.google.protobuf.LazyStringList columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureColumnNamesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          columnNames_ = new com.google.protobuf.LazyStringArrayList(columnNames_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string columnNames = 2;</code>
       */
      public java.util.List<java.lang.String>
          getColumnNamesList() {
        return java.util.Collections.unmodifiableList(columnNames_);
      }
      /**
       * <code>repeated string columnNames = 2;</code>
       */
      public int getColumnNamesCount() {
        return columnNames_.size();
      }
      /**
       * <code>repeated string columnNames = 2;</code>
       */
      public java.lang.String getColumnNames(int index) {
        return columnNames_.get(index);
      }
      /**
       * <code>repeated string columnNames = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColumnNamesBytes(int index) {
        return columnNames_.getByteString(index);
      }
      /**
       * <code>repeated string columnNames = 2;</code>
       */
      public Builder setColumnNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnNamesIsMutable();
        columnNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnNames = 2;</code>
       */
      public Builder addColumnNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnNamesIsMutable();
        columnNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnNames = 2;</code>
       */
      public Builder addAllColumnNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureColumnNamesIsMutable();
        super.addAll(values, columnNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnNames = 2;</code>
       */
      public Builder clearColumnNames() {
        columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnNames = 2;</code>
       */
      public Builder addColumnNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnNamesIsMutable();
        columnNames_.add(value);
        onChanged();
        return this;
      }

      // repeated string columnType = 3;
      private com.google.protobuf.LazyStringList columnType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureColumnTypeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          columnType_ = new com.google.protobuf.LazyStringArrayList(columnType_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string columnType = 3;</code>
       */
      public java.util.List<java.lang.String>
          getColumnTypeList() {
        return java.util.Collections.unmodifiableList(columnType_);
      }
      /**
       * <code>repeated string columnType = 3;</code>
       */
      public int getColumnTypeCount() {
        return columnType_.size();
      }
      /**
       * <code>repeated string columnType = 3;</code>
       */
      public java.lang.String getColumnType(int index) {
        return columnType_.get(index);
      }
      /**
       * <code>repeated string columnType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getColumnTypeBytes(int index) {
        return columnType_.getByteString(index);
      }
      /**
       * <code>repeated string columnType = 3;</code>
       */
      public Builder setColumnType(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnTypeIsMutable();
        columnType_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnType = 3;</code>
       */
      public Builder addColumnType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnTypeIsMutable();
        columnType_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnType = 3;</code>
       */
      public Builder addAllColumnType(
          java.lang.Iterable<java.lang.String> values) {
        ensureColumnTypeIsMutable();
        super.addAll(values, columnType_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnType = 3;</code>
       */
      public Builder clearColumnType() {
        columnType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnType = 3;</code>
       */
      public Builder addColumnTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnTypeIsMutable();
        columnType_.add(value);
        onChanged();
        return this;
      }

      // repeated string partitionColumnNames = 4;
      private com.google.protobuf.LazyStringList partitionColumnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePartitionColumnNamesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          partitionColumnNames_ = new com.google.protobuf.LazyStringArrayList(partitionColumnNames_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string partitionColumnNames = 4;</code>
       */
      public java.util.List<java.lang.String>
          getPartitionColumnNamesList() {
        return java.util.Collections.unmodifiableList(partitionColumnNames_);
      }
      /**
       * <code>repeated string partitionColumnNames = 4;</code>
       */
      public int getPartitionColumnNamesCount() {
        return partitionColumnNames_.size();
      }
      /**
       * <code>repeated string partitionColumnNames = 4;</code>
       */
      public java.lang.String getPartitionColumnNames(int index) {
        return partitionColumnNames_.get(index);
      }
      /**
       * <code>repeated string partitionColumnNames = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPartitionColumnNamesBytes(int index) {
        return partitionColumnNames_.getByteString(index);
      }
      /**
       * <code>repeated string partitionColumnNames = 4;</code>
       */
      public Builder setPartitionColumnNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePartitionColumnNamesIsMutable();
        partitionColumnNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string partitionColumnNames = 4;</code>
       */
      public Builder addPartitionColumnNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePartitionColumnNamesIsMutable();
        partitionColumnNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string partitionColumnNames = 4;</code>
       */
      public Builder addAllPartitionColumnNames(
          java.lang.Iterable<java.lang.String> values) {
        ensurePartitionColumnNamesIsMutable();
        super.addAll(values, partitionColumnNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string partitionColumnNames = 4;</code>
       */
      public Builder clearPartitionColumnNames() {
        partitionColumnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string partitionColumnNames = 4;</code>
       */
      public Builder addPartitionColumnNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePartitionColumnNamesIsMutable();
        partitionColumnNames_.add(value);
        onChanged();
        return this;
      }

      // required string fileName = 5;
      private java.lang.Object fileName_ = "";
      /**
       * <code>required string fileName = 5;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string fileName = 5;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fileName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileName = 5;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileName = 5;</code>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>required string fileName = 5;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fileName_ = value;
        onChanged();
        return this;
      }

      // required bool tableExist = 6;
      private boolean tableExist_ ;
      /**
       * <code>required bool tableExist = 6;</code>
       */
      public boolean hasTableExist() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bool tableExist = 6;</code>
       */
      public boolean getTableExist() {
        return tableExist_;
      }
      /**
       * <code>required bool tableExist = 6;</code>
       */
      public Builder setTableExist(boolean value) {
        bitField0_ |= 0x00000020;
        tableExist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool tableExist = 6;</code>
       */
      public Builder clearTableExist() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tableExist_ = false;
        onChanged();
        return this;
      }

      // required bool dropTable = 7;
      private boolean dropTable_ ;
      /**
       * <code>required bool dropTable = 7;</code>
       */
      public boolean hasDropTable() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required bool dropTable = 7;</code>
       */
      public boolean getDropTable() {
        return dropTable_;
      }
      /**
       * <code>required bool dropTable = 7;</code>
       */
      public Builder setDropTable(boolean value) {
        bitField0_ |= 0x00000040;
        dropTable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool dropTable = 7;</code>
       */
      public Builder clearDropTable() {
        bitField0_ = (bitField0_ & ~0x00000040);
        dropTable_ = false;
        onChanged();
        return this;
      }

      // required string delimiter = 8;
      private java.lang.Object delimiter_ = "";
      /**
       * <code>required string delimiter = 8;</code>
       */
      public boolean hasDelimiter() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string delimiter = 8;</code>
       */
      public java.lang.String getDelimiter() {
        java.lang.Object ref = delimiter_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          delimiter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string delimiter = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDelimiterBytes() {
        java.lang.Object ref = delimiter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          delimiter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string delimiter = 8;</code>
       */
      public Builder setDelimiter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        delimiter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string delimiter = 8;</code>
       */
      public Builder clearDelimiter() {
        bitField0_ = (bitField0_ & ~0x00000080);
        delimiter_ = getDefaultInstance().getDelimiter();
        onChanged();
        return this;
      }
      /**
       * <code>required string delimiter = 8;</code>
       */
      public Builder setDelimiterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        delimiter_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:knime.HiveOutput)
    }

    static {
      defaultInstance = new HiveOutput(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:knime.HiveOutput)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_knime_HiveOutput_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_knime_HiveOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020hiveOutput.proto\022\005knime\"\262\001\n\nHiveOutput" +
      "\022\021\n\ttableName\030\001 \002(\t\022\023\n\013columnNames\030\002 \003(\t" +
      "\022\022\n\ncolumnType\030\003 \003(\t\022\034\n\024partitionColumnN" +
      "ames\030\004 \003(\t\022\020\n\010fileName\030\005 \002(\t\022\022\n\ntableExi" +
      "st\030\006 \002(\010\022\021\n\tdropTable\030\007 \002(\010\022\021\n\tdelimiter" +
      "\030\010 \002(\tB8\n\035org.knime.python.kernel.protoB" +
      "\027ProtobufKnimeHiveOutput"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_knime_HiveOutput_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_knime_HiveOutput_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_knime_HiveOutput_descriptor,
              new java.lang.String[] { "TableName", "ColumnNames", "ColumnType", "PartitionColumnNames", "FileName", "TableExist", "DropTable", "Delimiter", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
