# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autocompletesuggestions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='autocompletesuggestions.proto',
  package='knime',
  serialized_pb='\n\x1d\x61utocompletesuggestions.proto\x12\x05knime\"\xb3\x01\n\x17\x41utocompleteSuggestions\x12U\n\x16\x61utocompleteSuggestion\x18\x01 \x03(\x0b\x32\x35.knime.AutocompleteSuggestions.AutocompleteSuggestion\x1a\x41\n\x16\x41utocompleteSuggestion\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\x0b\n\x03\x64oc\x18\x03 \x02(\tB@\n\x1dorg.knime.python.kernel.protoB\x1fProtobufAutocompleteSuggestions')




_AUTOCOMPLETESUGGESTIONS_AUTOCOMPLETESUGGESTION = _descriptor.Descriptor(
  name='AutocompleteSuggestion',
  full_name='knime.AutocompleteSuggestions.AutocompleteSuggestion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='knime.AutocompleteSuggestions.AutocompleteSuggestion.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='knime.AutocompleteSuggestions.AutocompleteSuggestion.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doc', full_name='knime.AutocompleteSuggestions.AutocompleteSuggestion.doc', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=155,
  serialized_end=220,
)

_AUTOCOMPLETESUGGESTIONS = _descriptor.Descriptor(
  name='AutocompleteSuggestions',
  full_name='knime.AutocompleteSuggestions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='autocompleteSuggestion', full_name='knime.AutocompleteSuggestions.autocompleteSuggestion', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_AUTOCOMPLETESUGGESTIONS_AUTOCOMPLETESUGGESTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=220,
)

_AUTOCOMPLETESUGGESTIONS_AUTOCOMPLETESUGGESTION.containing_type = _AUTOCOMPLETESUGGESTIONS;
_AUTOCOMPLETESUGGESTIONS.fields_by_name['autocompleteSuggestion'].message_type = _AUTOCOMPLETESUGGESTIONS_AUTOCOMPLETESUGGESTION
DESCRIPTOR.message_types_by_name['AutocompleteSuggestions'] = _AUTOCOMPLETESUGGESTIONS

class AutocompleteSuggestions(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class AutocompleteSuggestion(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _AUTOCOMPLETESUGGESTIONS_AUTOCOMPLETESUGGESTION

    # @@protoc_insertion_point(class_scope:knime.AutocompleteSuggestions.AutocompleteSuggestion)
  DESCRIPTOR = _AUTOCOMPLETESUGGESTIONS

  # @@protoc_insertion_point(class_scope:knime.AutocompleteSuggestions)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\035org.knime.python.kernel.protoB\037ProtobufAutocompleteSuggestions')
# @@protoc_insertion_point(module_scope)
