# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remoteFileInput.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remoteFileInput.proto',
  package='knime',
  serialized_pb='\n\x15remoteFileInput.proto\x12\x05knime\"\x95\x01\n\x0fRemoteFileInput\x12\x10\n\x08protocol\x18\x01 \x02(\t\x12\x0c\n\x04host\x18\x02 \x02(\t\x12\x0c\n\x04port\x18\x03 \x02(\x05\x12\x0c\n\x04user\x18\x04 \x02(\t\x12\x10\n\x08password\x18\x05 \x02(\t\x12\x0f\n\x07keyfile\x18\x06 \x01(\t\x12\x12\n\nknownHosts\x18\x07 \x01(\t\x12\x0f\n\x07timeout\x18\x08 \x02(\x05\x42=\n\x1dorg.knime.python.kernel.protoB\x1cProtobufKnimeRemoteFileInput')




_REMOTEFILEINPUT = _descriptor.Descriptor(
  name='RemoteFileInput',
  full_name='knime.RemoteFileInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol', full_name='knime.RemoteFileInput.protocol', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host', full_name='knime.RemoteFileInput.host', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='knime.RemoteFileInput.port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='knime.RemoteFileInput.user', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='knime.RemoteFileInput.password', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keyfile', full_name='knime.RemoteFileInput.keyfile', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='knownHosts', full_name='knime.RemoteFileInput.knownHosts', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='knime.RemoteFileInput.timeout', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=182,
)

DESCRIPTOR.message_types_by_name['RemoteFileInput'] = _REMOTEFILEINPUT

class RemoteFileInput(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REMOTEFILEINPUT

  # @@protoc_insertion_point(class_scope:knime.RemoteFileInput)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\035org.knime.python.kernel.protoB\034ProtobufKnimeRemoteFileInput')
# @@protoc_insertion_point(module_scope)
