# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sqlOutput.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sqlOutput.proto',
  package='knime',
  serialized_pb='\n\x0fsqlOutput.proto\x12\x05knime\"\x1a\n\tSQLOutput\x12\r\n\x05query\x18\x05 \x02(\tB7\n\x1dorg.knime.python.kernel.protoB\x16ProtobufKnimeSQLOutput')




_SQLOUTPUT = _descriptor.Descriptor(
  name='SQLOutput',
  full_name='knime.SQLOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='knime.SQLOutput.query', index=0,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['SQLOutput'] = _SQLOUTPUT

class SQLOutput(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SQLOUTPUT

  # @@protoc_insertion_point(class_scope:knime.SQLOutput)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\035org.knime.python.kernel.protoB\026ProtobufKnimeSQLOutput')
# @@protoc_insertion_point(module_scope)
