# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: variablelist.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='variablelist.proto',
  package='knime',
  serialized_pb='\n\x12variablelist.proto\x12\x05knime\"t\n\x0cVariableList\x12.\n\x08variable\x18\x01 \x03(\x0b\x32\x1c.knime.VariableList.Variable\x1a\x34\n\x08Variable\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\tB5\n\x1dorg.knime.python.kernel.protoB\x14ProtobufVariableList')




_VARIABLELIST_VARIABLE = _descriptor.Descriptor(
  name='Variable',
  full_name='knime.VariableList.Variable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='knime.VariableList.Variable.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='knime.VariableList.Variable.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='knime.VariableList.Variable.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=93,
  serialized_end=145,
)

_VARIABLELIST = _descriptor.Descriptor(
  name='VariableList',
  full_name='knime.VariableList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variable', full_name='knime.VariableList.variable', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_VARIABLELIST_VARIABLE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=145,
)

_VARIABLELIST_VARIABLE.containing_type = _VARIABLELIST;
_VARIABLELIST.fields_by_name['variable'].message_type = _VARIABLELIST_VARIABLE
DESCRIPTOR.message_types_by_name['VariableList'] = _VARIABLELIST

class VariableList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Variable(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _VARIABLELIST_VARIABLE

    # @@protoc_insertion_point(class_scope:knime.VariableList.Variable)
  DESCRIPTOR = _VARIABLELIST

  # @@protoc_insertion_point(class_scope:knime.VariableList)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\035org.knime.python.kernel.protoB\024ProtobufVariableList')
# @@protoc_insertion_point(module_scope)
