<script setup lang="ts">
import { onMounted, ref } from "vue";

import { KdsEmptyState } from "@knime/kds-components";

import { usePythonPreviewStatusStore } from "@/store";

const IFRAME_SOURCE = "./preview.html";

const iframe = ref<HTMLIFrameElement | null>(null);
const pythonPreviewStatus = usePythonPreviewStatusStore();

onMounted(() => {
  pythonPreviewStatus.updateViewCallback = () => {
    // NB: This is a workaround to force the iframe to reload the content
    // "replace" is allowed by the same-origin policy on the sandboxed iframe
    // see https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#location
    iframe.value?.contentWindow?.location.replace(IFRAME_SOURCE);
  };
});
</script>

<template>
  <div class="container">
    <div v-show="pythonPreviewStatus.hasValidView" class="iframe-container">
      <iframe
        ref="iframe"
        title="Preview"
        sandbox="allow-scripts"
        :src="IFRAME_SOURCE"
      />
    </div>
    <div v-if="!pythonPreviewStatus.hasValidView" class="empty-state-container">
      <KdsEmptyState
        v-if="!pythonPreviewStatus.isExecutedOnce"
        headline="Run the code to see the preview"
        description="Views generated by the Python script will be displayed here."
      />
      <KdsEmptyState
        v-else
        headline="The view cannot be displayed"
        description="Check the error message and re-execute the script."
      />
    </div>
  </div>
</template>

<style scoped lang="postcss">
iframe,
.iframe-container,
.container {
  display: block;
  width: 100%;
  height: 100%;
  border: none;
}

.empty-state-container {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
}
</style>
