import { beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { mount } from "@vue/test-utils";

import { KdsEmptyState } from "@knime/kds-components";
import { getScriptingService } from "@knime/scripting-editor";

import { usePythonPreviewStatusStore } from "@/store";
import PythonViewPreview from "../PythonViewPreview.vue";

describe("PythonViewPreview", () => {
  const previewStatusStore = usePythonPreviewStatusStore();
  const sendToServiceMock = vi.fn();

  beforeAll(() => {
    getScriptingService().sendToService = sendToServiceMock;
  });

  beforeEach(() => {
    previewStatusStore.hasValidView = false;
    previewStatusStore.isExecutedOnce = false;
    delete previewStatusStore.updateViewCallback;
  });

  it("renders iframe", () => {
    previewStatusStore.hasValidView = true;
    const wrapper = mount(PythonViewPreview);
    const iframe = wrapper.find("iframe");
    expect(iframe.exists()).toBeTruthy();
    expect(iframe.attributes("sandbox")).toBe("allow-scripts");
    expect(iframe.attributes("src")).toBe("./preview.html");
  });

  it("adds update view callback on mount", () => {
    mount(PythonViewPreview);
    expect(previewStatusStore.updateViewCallback).toBeDefined();
  });

  it("replaces iframe when update view callback is called", () => {
    previewStatusStore.hasValidView = true;
    // Mock the iframe's contentWindow
    const mockIframeContentWindow = {
      location: {
        replace: vi.fn(),
      },
    };

    // Use Object.defineProperty to mock the iframe's contentWindow
    Object.defineProperty(window.HTMLIFrameElement.prototype, "contentWindow", {
      get: () => mockIframeContentWindow,
      configurable: true,
    });

    mount(PythonViewPreview);

    // mock updating the view via the provided callback
    const store = usePythonPreviewStatusStore();
    store.updateViewCallback!();

    expect(mockIframeContentWindow.location.replace).toHaveBeenCalled();

    delete store.updateViewCallback;
  });

  it("shows view if valid view exists", () => {
    previewStatusStore.hasValidView = true;
    const wrapper = mount(PythonViewPreview);
    expect(wrapper.find(".iframe-container").isVisible()).toBeTruthy();
    expect(wrapper.find(".empty-state-container").exists()).toBeFalsy();
  });

  describe("empty-state", () => {
    it("shows empty state component if valid view does not exist", () => {
      const wrapper = mount(PythonViewPreview);
      expect(wrapper.find(".iframe-container").isVisible()).toBeFalsy();
      expect(wrapper.find(".empty-state-container").isVisible()).toBeTruthy();
      expect(wrapper.findComponent(KdsEmptyState).exists()).toBeTruthy();
    });

    it("shows empty state component before first execution", () => {
      const wrapper = mount(PythonViewPreview);
      const emptyState = wrapper.findComponent(KdsEmptyState);
      expect(wrapper.find(".iframe-container").isVisible()).toBeFalsy();
      expect(wrapper.find(".empty-state-container").isVisible()).toBeTruthy();
      expect(emptyState.props().headline).toBe(
        "Run the code to see the preview",
      );
      expect(emptyState.props().description).toBe(
        "Views generated by the Python script will be displayed here.",
      );
    });

    it("shows error text after first execution", () => {
      previewStatusStore.isExecutedOnce = true;
      const wrapper = mount(PythonViewPreview);
      const emptyState = wrapper.findComponent(KdsEmptyState);
      expect(wrapper.find(".iframe-container").isVisible()).toBeFalsy();
      expect(wrapper.find(".empty-state-container").isVisible()).toBeTruthy();
      expect(emptyState.props().headline).toBe("The view cannot be displayed");
      expect(emptyState.props().description).toBe(
        "Check the error message and re-execute the script.",
      );
    });
  });
});
