# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatc

import flatbuffers

class LongCollectionColumn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLongCollectionColumn(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LongCollectionColumn()
        x.Init(buf, n + offset)
        return x

    # LongCollectionColumn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LongCollectionColumn
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .LongCollectionCell import LongCollectionCell
            obj = LongCollectionCell()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LongCollectionColumn
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LongCollectionColumn
    def Missing(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # LongCollectionColumn
    def MissingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def LongCollectionColumnStart(builder): builder.StartObject(2)
def LongCollectionColumnAddValues(builder, values): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)
def LongCollectionColumnStartValuesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LongCollectionColumnAddMissing(builder, missing): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(missing), 0)
def LongCollectionColumnStartMissingVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def LongCollectionColumnEnd(builder): return builder.EndObject()
