/*
 * ------------------------------------------------------------------------
 *  Copyright by KNIME AG, Zurich, Switzerland
 *  Website: http://www.knime.com; Email: contact@knime.com
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License, Version 3, as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 *  Additional permission under GNU GPL version 3 section 7:
 *
 *  KNIME interoperates with ECLIPSE solely via ECLIPSE's plug-in APIs.
 *  Hence, KNIME and ECLIPSE are both independent programs and are not
 *  derived from each other. Should, however, the interpretation of the
 *  GNU GPL Version 3 ("License") under any applicable laws result in
 *  KNIME and ECLIPSE being a combined program, KNIME AG herewith grants
 *  you the additional permission to use and propagate KNIME together with
 *  ECLIPSE with only the license terms in place for ECLIPSE applying to
 *  ECLIPSE and the GNU GPL Version 3 applying for KNIME, provided the
 *  license terms of ECLIPSE themselves allow for the respective use and
 *  propagation of ECLIPSE together with KNIME.
 *
 *  Additional permission relating to nodes for KNIME that extend the Node
 *  Extension (and in particular that are based on subclasses of NodeModel,
 *  NodeDialog, and NodeView) and that only interoperate with KNIME through
 *  standard APIs ("Nodes"):
 *  Nodes are deemed to be separate and independent programs and to not be
 *  covered works.  Notwithstanding anything to the contrary in the
 *  License, the License does not apply to Nodes, you are not required to
 *  license Nodes under the License, and you are granted a license to
 *  prepare and propagate Nodes, in each case even if such Nodes are
 *  propagated with or for interoperation with KNIME.  The owner of a Node
 *  may freely choose the license terms applicable to such Node, including
 *  when such Node is propagated with or for interoperation with KNIME.
 * ------------------------------------------------------------------------
 */

// automatically generated by the FlatBuffers compiler, do not modify

package org.knime.python2.serde.flatbuffers.flatc;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("javadoc")
public final class KnimeTable extends Table {
    private int m_length;

    private int m_lengthsVecPos;

    private int m_strVecPos;

    public static KnimeTable getRootAsKnimeTable(final ByteBuffer _bb) {
        return getRootAsKnimeTable(_bb, new KnimeTable());
    }

    public static KnimeTable getRootAsKnimeTable(final ByteBuffer _bb, final KnimeTable obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(final int _i, final ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
        initVectorPositions();
    }

    public KnimeTable __assign(final int _i, final ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    private void initVectorPositions() {
        final int o = __offset(4);
        int l = __vector_len(o);
        // [0] offset from the buffer end where the rowIDs vector starts
        // [1] offset from the buffer end where the vector containing the rowIDs vector elements' lengths starts
        int[] offsets = new int[l];
        bb.position(__vector(o));
        bb.asIntBuffer().get(offsets);
        //offset from the buffers end, first element is length => +len(int32)
        m_lengthsVecPos = bb.limit() - offsets[1] + 4;
        m_strVecPos = bb.limit() - offsets[0] + 4;
        //values length = length in bytes / 4
        m_length = bb.getInt(bb.limit() - offsets[1]) / 4;
    }

    public String rowID(final int j) {
        bb.position(m_lengthsVecPos);
        int strLen = bb.getInt();
        m_lengthsVecPos += 4;
        bb.position(m_strVecPos);
        byte[] dst = new byte[strLen];
        bb.get(dst);
        m_strVecPos += strLen;
        return new String(dst, StandardCharsets.UTF_8);
    }

    public int rowIDsLength() {
        return m_length;
    }

    public String colNames(final int j) {
        final int o = __offset(6);
        return o != 0 ? __string(__vector(o) + (j * 4)) : null;
    }

    public int colNamesLength() {
        final int o = __offset(6);
        return o != 0 ? __vector_len(o) : 0;
    }

    public Column columns(final int j) {
        return columns(new Column(), j);
    }

    public Column columns(final Column obj, final int j) {
        final int o = __offset(8);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + (j * 4)), bb) : null;
    }

    public int columnsLength() {
        final int o = __offset(8);
        return o != 0 ? __vector_len(o) : 0;
    }

    public static int createKnimeTable(final FlatBufferBuilder builder, final int rowIDsOffset,
        final int colNamesOffset, final int columnsOffset) {
        builder.startObject(3);
        KnimeTable.addColumns(builder, columnsOffset);
        KnimeTable.addColNames(builder, colNamesOffset);
        KnimeTable.addRowIDs(builder, rowIDsOffset);
        return KnimeTable.endKnimeTable(builder);
    }

    public static void startKnimeTable(final FlatBufferBuilder builder) {
        builder.startObject(3);
    }

    public static void addRowIDs(final FlatBufferBuilder builder, final int rowIDsOffset) {
        builder.addOffset(0, rowIDsOffset, 0);
    }

    public static int createRowIDsVector(final FlatBufferBuilder builder, final int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }

    public static void startRowIDsVector(final FlatBufferBuilder builder, final int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addColNames(final FlatBufferBuilder builder, final int colNamesOffset) {
        builder.addOffset(1, colNamesOffset, 0);
    }

    public static int createColNamesVector(final FlatBufferBuilder builder, final int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }

    public static void startColNamesVector(final FlatBufferBuilder builder, final int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addColumns(final FlatBufferBuilder builder, final int columnsOffset) {
        builder.addOffset(2, columnsOffset, 0);
    }

    public static int createColumnsVector(final FlatBufferBuilder builder, final int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }

    public static void startColumnsVector(final FlatBufferBuilder builder, final int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static int endKnimeTable(final FlatBufferBuilder builder) {
        final int o = builder.endObject();
        return o;
    }

    public static void finishKnimeTableBuffer(final FlatBufferBuilder builder, final int offset) {
        builder.finish(offset);
    }
}
