// automatically generated by the FlatBuffers compiler, do not modify

package org.knime.python2.serde.flatbuffers.flatc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class KnimeTable extends Table {
  public static KnimeTable getRootAsKnimeTable(ByteBuffer _bb) { return getRootAsKnimeTable(_bb, new KnimeTable()); }
  public static KnimeTable getRootAsKnimeTable(ByteBuffer _bb, KnimeTable obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public KnimeTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String rowIDs(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int rowIDsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public String colNames(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int colNamesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public Column columns(int j) { return columns(new Column(), j); }
  public Column columns(Column obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int columnsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }

  public static int createKnimeTable(FlatBufferBuilder builder,
      int rowIDsOffset,
      int colNamesOffset,
      int columnsOffset) {
    builder.startObject(3);
    KnimeTable.addColumns(builder, columnsOffset);
    KnimeTable.addColNames(builder, colNamesOffset);
    KnimeTable.addRowIDs(builder, rowIDsOffset);
    return KnimeTable.endKnimeTable(builder);
  }

  public static void startKnimeTable(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addRowIDs(FlatBufferBuilder builder, int rowIDsOffset) { builder.addOffset(0, rowIDsOffset, 0); }
  public static int createRowIDsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRowIDsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addColNames(FlatBufferBuilder builder, int colNamesOffset) { builder.addOffset(1, colNamesOffset, 0); }
  public static int createColNamesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startColNamesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addColumns(FlatBufferBuilder builder, int columnsOffset) { builder.addOffset(2, columnsOffset, 0); }
  public static int createColumnsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startColumnsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKnimeTable(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishKnimeTableBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

