# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatc

import flatbuffers

class BooleanCollectionCell(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBooleanCollectionCell(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BooleanCollectionCell()
        x.Init(buf, n + offset)
        return x

    # BooleanCollectionCell
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BooleanCollectionCell
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BooleanCollectionCell
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def BooleanCollectionCellStart(builder): builder.StartObject(1)
def BooleanCollectionCellAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def BooleanCollectionCellStartValueVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def BooleanCollectionCellEnd(builder): return builder.EndObject()
