# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatc

import flatbuffers

class BooleanCollectionColumn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBooleanCollectionColumn(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BooleanCollectionColumn()
        x.Init(buf, n + offset)
        return x

    # BooleanCollectionColumn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BooleanCollectionColumn
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .BooleanCollectionCell import BooleanCollectionCell
            obj = BooleanCollectionCell()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BooleanCollectionColumn
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def BooleanCollectionColumnStart(builder): builder.StartObject(1)
def BooleanCollectionColumnAddValues(builder, values): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)
def BooleanCollectionColumnStartValuesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def BooleanCollectionColumnEnd(builder): return builder.EndObject()
