# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatc

import flatbuffers

class Header(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHeader(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Header()
        x.Init(buf, n + offset)
        return x

    # Header
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Header
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def HeaderStart(builder): builder.StartObject(1)
def HeaderAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def HeaderEnd(builder): return builder.EndObject()
