# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatc

import flatbuffers

class IntegerCollectionCell(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIntegerCollectionCell(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntegerCollectionCell()
        x.Init(buf, n + offset)
        return x

    # IntegerCollectionCell
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntegerCollectionCell
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # IntegerCollectionCell
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def IntegerCollectionCellStart(builder): builder.StartObject(1)
def IntegerCollectionCellAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def IntegerCollectionCellStartValueVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def IntegerCollectionCellEnd(builder): return builder.EndObject()
