# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatc

import flatbuffers

class StringColumn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStringColumn(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StringColumn()
        x.Init(buf, n + offset)
        return x

    # StringColumn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StringColumn
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # StringColumn
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def StringColumnStart(builder): builder.StartObject(1)
def StringColumnAddValues(builder, values): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)
def StringColumnStartValuesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StringColumnEnd(builder): return builder.EndObject()
